module.exports = [{
    reg: 'map.json',
    release: false
}, {
    // component.json, *.md, _xxx.oo, xxx.inline.oo, *.sh, *.bat
    reg: /^\/(component\.json|.*\.md|([^\/]+\/)*_[^\/]+\.\w+|.*\.inline\.\w+|.*\.sh|.*\.bat)$/i,
    release: false
}, {
    reg: /^\/views\/.*view\.json$/i,
    release: false
}, {
    reg: /^\/views\/([^\/]+)\/\1\.html$/i,
    isView: true
}, {
    reg: /^\/views\/[^\/]+\.html$/i,
    isView: true
}, {
    reg: /^\/views\/(.+)$/i,
    id: 'v/$1',
    release : '/lego/v/$1',
    url: '/s/uae/g/06/lego/v/$1'
}, {
    reg: '**.handlebars',
    release: false,
    isJsLike: true
}, {
    reg: /^\/units\/.*?unit\.json$/i,
    release: false
}, {
    reg: /^\/units\/[^\/]+\/data\.js$/i,
    useCompile: false
}, {
    reg: /^\/units\/([^\/]+)\/\1\.ejs$/i,
    isHtmlLike: true,
    isMod: true,
    isUnit: true
}, {
    reg: /^\/units\/([^\/]+)\/(\1\.(?:js|css))$/i,
    id: '${lego.hash}/u/$1/$2',
    release: '/lego/${lego.code}/${lego.hash}/u/$1/$2',
    url: '/s/uae/g/06/lego/${lego.code}/${lego.hash}/u/$1/$2',
    isMod: true,
    isUnit: true,
    useHash: false,
    useSprite: true
}, {
    reg: /^\/units\/([^\/]+)\/\1\.(?:styl|less)$/i,
    id: '${lego.hash}/u/$1/$1.css',
    release: '/lego/${lego.code}/${lego.hash}/u/$1/$1.css',
    url: '/s/uae/g/06/lego/${lego.code}/${lego.hash}/u/$1/$1.css',
    isMod: true,
    isUnit: true,
    useHash: false,
    useSprite: true
}, {
    reg: /^\/units\/(.+\.(?:js|css))$/i,
    id: '${lego.hash}/u/$1',
    release: '/lego/${lego.code}/${lego.hash}/u/$1',
    url: '/s/uae/g/06/lego/${lego.code}/${lego.hash}/u/$1',
    isMod: true,
    useHash: false,
    useSprite: true
}, {
    reg: /^\/units\/(.+)\.(?:styl|less)$/i,
    id: '${lego.hash}/u/$1.css',
    release: '/lego/${lego.code}/${lego.hash}/u/$1.css',
    url: '/s/uae/g/06/lego/${lego.code}/${lego.hash}/u/$1.css',
    isMod: true,
    useHash: false,
    useSprite: true
}, {
    reg: /^\/units\/(.+)$/i,
    id: '${lego.hash}/u/$1',
    release: '/lego/${lego.code}/${lego.hash}/u/$1',
    url: '/s/uae/g/06/lego/${lego.code}/${lego.hash}/u/$1'
}, {
    reg: /^\/components\/(.+)\.(?:styl|less)$/i,
    id: '${lego.hash}/c/$1.css',
    release: '/lego/${lego.code}/${lego.hash}/c/$1.css',
    url: '/s/uae/g/06/lego/${lego.code}/${lego.hash}/c/$1.css',
    isMod: true,
    useHash: false,
    useSprite: true
}, {
    reg: /^\/components\/(.+\.(?:js|css))$/i,
    id: '${lego.hash}/c/$1',
    release: '/lego/${lego.code}/${lego.hash}/c/$1',
    url: '/s/uae/g/06/lego/${lego.code}/${lego.hash}/c/$1',
    isMod: true,
    useHash: false,
    useSprite: true
}, {
    reg: /^\/components\/(.+)$/i,
    id: '${lego.hash}/c/$1',
    release: '/lego/${lego.code}/${lego.hash}/c/$1',
    url: '/s/uae/g/06/lego/${lego.code}/${lego.hash}/c/$1'
}, {
    reg: '**',
    useHash: false,
    useCompile: false,
    isOther: true
}];